apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: load-balancer
  namespace: metallb
spec:
  addresses:
    - 172.18.0.10-172.18.0.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb
spec:
  ipAddressPools:
    - load-balancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-0-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.10
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-0  
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-1-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.11
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-1 
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-2-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.12
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-2
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-3-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.13
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-3
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-repl-0-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.110
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: mariadb-repl
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-repl-0
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-repl-1-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.111
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: mariadb-repl
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-repl-1
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-repl-2-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.112
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: mariadb-repl
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-repl-2
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-repl-3-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.113
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: mariadb-repl
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-repl-3
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera-0-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.140
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: mariadb-galera
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-galera-0
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera-1-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.141
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: mariadb-galera
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-galera-1
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera-2-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.142
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: mariadb-galera
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-galera-2
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-galera-3-lb
  namespace: default
  annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.143
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: mariadb-galera
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mariadb-galera-3
  type: LoadBalancer