nameOverride: ""
fullnameOverride: ""

image:
  repository: mmontes11/mariadb-operator
  pullPolicy: IfNotPresent
  tag: v0.0.2

logLevel: INFO

clusterName: cluster.local

ha:
  enabled: true
  replicas: 3
  leaseId: database.mmontes.io

monitoring:
  enabled: true
  prometheusRelease: kube-prometheus-stack

podAnnotations: {}

podSecurityContext:
  allowPrivilegeEscalation: false

securityContext:
  runAsNonRoot: true

resources:
  manager:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  rbacProxy:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
