[default.extend-words]
# HashiCorp
hashi = "hashi"
# Incremental State Transfers
ist = "ist"
# TO DO: fix => immutable
inmutable = "inmutable"
# Global Transaction IDs
GTI = "GTI"
# Global Transaction IDs
GTIDs = "GTIDs"
# Global Transaction ID
GTID = "GTID"
[files]
extend-exclude = [
    # comes from external source
    "pkg/embed/mariadb-docker/**",
    # false-postitives in certs
    "pkg/pki/*test.go",
]