apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: sbtest
spec:
  name: sbtest
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci
  requeueInterval: 30s
  retryInterval: 5s