apiVersion: batch/v1
kind: CronJob
metadata:
  name: sysbench-galera
spec:
  concurrencyPolicy: Forbid
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: sysbench-prepare
            image: zyclonite/sysbench:1.0.21
            command:
              - sysbench
              - oltp_read_write
              - --tables=5
              - --table_size=1000000
              # - --mysql-host=mariadb-galera-primary.default.svc.cluster.local
              - --mysql-host=maxscale-galera.default.svc.cluster.local
              - --mysql-port=3306
              - --mysql-user=sbtest-galera
              - --mysql-password=MariaDB11!
              - --mysql-db=sbtest-galera
              # - --mysql-ssl=on
              # - --mysql-ssl-cipher=AES256
              - --time=300 
              - --threads=64
              - --report-interval=1
              - run
            # volumeMounts:
            #   - name: pki
            #     mountPath: /etc/pki
            #     readOnly: true
            # workingDir: /etc/pki
            # resources:
            #   requests:
            #     cpu: 500m
            #     memory: 128Mi
            #   limits:
            #     memory: 512Mi
          # volumes:
          #   - name: pki
          #     projected:
          #       sources:
          #         - secret:
          #             # name: mariadb-galera-ca-bundle
          #             name: maxscale-galera-ca-bundle
          #             items:
          #               - key: ca.crt
          #                 path: cacert.pem
          #         - secret:
          #             name: mariadb-galera-client-cert
          #             items:
          #               - key: tls.crt
          #                 path: client-cert.pem
          #               - key: tls.key
          #                 path: client-key.pem