{{ if .Values.webhook.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-serving-cert
spec:
  dnsNames:
    - {{ include "mariadb-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "mariadb-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "mariadb-operator.fullname" . }}-selfsigned-issuer
  secretName: {{ include "mariadb-operator.fullname" . }}-webhook-server-cert
{{ end }}