apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mariadb-operator.fullname" . }}
  labels:
    {{ include "mariadb-operator.labels" . | nindent 4 }}
spec:
  {{ if .Values.ha.enabled }}
  replicas: {{ .Values.ha.replicas}}
  {{ end }}
  selector:
    matchLabels:
      {{ include "mariadb-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{ with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      labels:
        {{ include "mariadb-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: mariadb-controller-manager
      terminationGracePeriodSeconds: 10
      {{ with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: controller
          args:
            - --metrics-addr=:8080
            - --log-level={{ .Values.logLevel }}
            {{ if .Values.ha.enabled }}
            - --leader-elect
            {{ end }}
            {{ if .Values.metrics.enabled }}
            - --service-monitor-reconciler
            {{ end }}
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
          env: 
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
          {{ with .Values.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          {{ with .Values.podSecurityContext}}
          securityContext:
            {{ toYaml . | nindent 12 }}
          {{ end }}