{{ if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-metrics-service
  labels:
    {{- include "mariadb-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "mariadb-operator.selectorLabels" . | nindent 4 }}
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-webhook-service
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "mariadb-operator.selectorLabels" . | nindent 4 }}