{{- if not .Values.webhook.certificate.certManager }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-webhook-ca
  labels:
    {{- include "mariadb-operator-webhook.labels" . | nindent 4 }}
    mariadb-operator.io/component: webhook
  {{- with .Values.webhook.certificate.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb-operator.fullname" . }}-webhook-cert
  labels:
    {{- include "mariadb-operator-webhook.labels" . | nindent 4 }}
    mariadb-operator.io/component: webhook
  {{- with .Values.webhook.certificate.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
