apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: database
spec:
  # If you want the database to be created with a different name than the resource name
  # name: my-logical-database
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci
  requeueInterval: 30s
  retryInterval: 5s