# Please, take a look at our HA guide to configure production-ready MariaDB instances:
# https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/high_availability.md
# Configure a backup and recovery strategy in case that something goes wrong:
# https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/physical_backup.md
# Roll out upgrades choosing the right upgrade strategy:
# https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/updates.md
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  # Point to an existing MaxScale instance. Doing this will delegate operations such as primary failover to MaxScale.
  # maxScaleRef:
  #   name: maxscale-repl

  storage:
    size: 10Gi

  # Recreate the MariaDB resource and bootstrap from a physical backup in S3.
  # bootstrapFrom:
  #   s3:
  #     bucket: physicalbackups
  #     prefix: mariadb
  #     endpoint: minio.minio.svc.cluster.local:9000
  #     accessKeyIdSecretKeyRef:
  #       name: minio
  #       key: access-key-id
  #     secretAccessKeySecretKeyRef:
  #       name: minio
  #       key: secret-access-key
  #     tls:
  #       enabled: true
  #       caSecretKeyRef:
  #         name: minio-ca
  #         key: ca.crt
  #   backupContentType: Physical
  #   targetRecoveryTime: 2023-12-19T09:00:00Z
  #   stagingStorage:
  #     persistentVolumeClaim:
  #       resources:
  #         requests:
  #           storage: 10Gi
  #       accessModes:
  #         - ReadWriteOnce
  #   restoreJob:
  #     resources:
  #       requests:
  #         cpu: 100m
  #         memory: 128Mi
  #       limits:
  #         memory: 1Gi

  replicas: 3

  replication:
    # Enable semi-synchronous replication.
    enabled: true
    primary:
      # Whether the operator should automatically perform primary failover.
      autoFailover: true
      # Duration before performing primary failover.
      autoFailoverDelay: 0s
      # Trigger a switchover by declaring the desired primary index.
      # podIndex: 0
    replica:
      # Password for the replication user used by the replicas to connect to the primary.
      replPasswordSecretKeyRef:
        name: mariadb
        key: password
      # Define the data source to bootstrap new replicas from.
      bootstrapFrom:
        # Reference to a PhysicalBackup object to be used as a template to bootstrap new replicas.
        physicalBackupTemplateRef:
          name: physicalbackup-tpl
      recovery:
        # When replicas enter an error state, trigger the recovery process.
        # Replicas erroring with known error codes will trigger the recovery immediately.
        enabled: true
        # Replicas erroring with unknown error codes will trigger the process after 5m.
        # errorDurationThreshold: 5m
    # Enables GTID strict mode.
    # See: See: https://mariadb.com/docs/server/ha-and-performance/standard-replication/gtid#gtid_strict_mode.
    gtidStrictMode: true

  # service:
  #   type: LoadBalancer
  #   metadata:
  #     annotations:
  #       metallb.universe.tf/loadBalancerIPs: 172.18.0.120

  # primaryService:
  #   type: LoadBalancer
  #   metadata:
  #     annotations:
  #       metallb.universe.tf/loadBalancerIPs: 172.18.0.130

  # secondaryService:
  #   type: LoadBalancer
  #   metadata:
  #     annotations:
  #       metallb.universe.tf/loadBalancerIPs: 172.18.0.131

  metrics:
    enabled: true

  # Issue and configure TLS certificates. For enhanced security, TLS will be enforced in all connections .
  tls:
    enabled: true
    required: true

  updateStrategy:
    type: ReplicasFirstPrimaryLast
    # Pause updates.
    # type: Never
    # Update the data-plane after an operator upgrade.
    # autoUpdateDataPlane: true

  # Configure enough compute resources. This is just an example, take a look at your historic compute metrics to estimate.
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      memory: 4Gi

  # Tune your liveness probe accordingly to avoid Pod restarts.
  livenessProbe:
    periodSeconds: 5
    timeoutSeconds: 5

  # Tune your readiness probe accordingly to prevent disruptions in network traffic.
  readinessProbe:
    periodSeconds: 5
    timeoutSeconds: 5

  # Tune your startup probe accordingly to the delay needed for full sst completion.
  startupProbe:
    failureThreshold: 10
    periodSeconds: 5
    timeoutSeconds: 5

  # innodb_buffer_pool_size: 80% of memory limits.
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=3200MB
    max_allowed_packet=1GB

  # Select a node type with enough compute capacity.
  nodeSelector:
    kubernetes.io/arch: amd64  

  # Schedule Pods in different Nodes to achieve real HA.
  affinity:
    antiAffinityEnabled: true

  # When draining Nodes, make sure that you have at least 2 Pods available.
  podDisruptionBudget:
    maxUnavailable: 66%

  # Ensure that the Pods are not preempted by Kubernetes to make room for new scheduled Pods.
  priorityClassName: system-node-critical

---
# PhysicalBackup object to be used as template to bootstrap new replicas.
apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: physicalbackup-tpl
spec:
  mariaDbRef:
    name: mariadb-repl
    waitForIt: false
  schedule:
    suspend: true
  target: PreferReplica
  storage:
    s3:
      bucket: scaleout
      prefix: mariadb
      endpoint: minio.minio.svc.cluster.local:9000
      region:  us-east-1
      accessKeyIdSecretKeyRef:
        name: minio
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: minio
        key: secret-access-key
      tls:
        enabled: true
        caSecretKeyRef:
          name: minio-ca
          key: ca.crt
  timeout: 1h
  podAffinity: true
  stagingStorage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 1Gi
      accessModes:
        - ReadWriteOnce