apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-from-pvc
spec:
  storage:
    size: 1Gi

  bootstrapFrom:
    volume:
      persistentVolumeClaim:
        claimName: backup-scheduled
    targetRecoveryTime: 2023-12-19T09:00:00Z