apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-init-mariabackup
spec:
  # See: https://mariadb.com/kb/en/full-backup-and-restore-with-mariabackup/
  initContainers:
    - image: docker-registry1.mariadb.com/library/mariadb:10.11.8
      args:
        - mariadb-backup 
        - --copy-back 
        - --target-dir=/var/mariadb/backup/

  volumes: 
    - name: mariabackup
      persistentVolumeClaim:
        claimName: mariabackup
  volumeMounts: 
    - name: mariabackup
      mountPath: /var/mariadb/backup/

  storage:
    size: 1Gi