apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  # metadata that will be inherited by all children objects
  inheritMetadata:
    labels:
      database.myorg.io: mariadb  
    annotations:
      database.myorg.io: mariadb

  storage:
    size: 1Gi
