apiVersion: mariadb.mmontes.io/v1alpha1
kind: MaxScale
metadata:
  name: maxscale-galera
spec:
  mariaDbRef:
    name: mariadb-galera

  kubernetesService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.224