apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  # metadata that will be inherited by all children objects
  inheritMetadata:
    labels:
      database.myorg.io: mariadb  
    annotations:
      database.myorg.io: mariadb

  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  image:
    repository: mariadb
    tag: "11.0.2"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    spec:
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce
