apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-from-backup
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password

  image:
    repository: mariadb
    tag: "10.11.3"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 100Mi
    storageClassName: standard
    accessModes:
      - ReadWriteOnce

  bootstrapFrom:
    backupRef:
      name: backup-scheduled

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  env:
    - name: TZ
      value: SYSTEM

  envFrom:
    - configMapRef:
        name: mariadb
