apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password
  connection:
    secretName: connection-mariadb
    secretTemplate:
      key: dsn
    healthCheck:
      interval: 10s
      retryInterval: 3s

  image:
    repository: mariadb
    tag: "10.7.4"
    pullPolicy: IfNotPresent

  port: 3306

  volumeClaimTemplate:
    resources:
      requests:
        storage: 100Mi
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
