apiVersion: v1
kind: Service
metadata:
  name: maxscale-repl-0-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.210
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: maxscale-repl
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: maxscale-repl-0  
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: maxscale-repl-1-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.211
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: maxscale-repl
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: maxscale-repl-1 
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: maxscale-repl-2-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.212
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: maxscale-repl
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: maxscale-repl-2
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: maxscale-repl-3-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.213
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: maxscale-repl
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: maxscale-repl-3
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-repl-maxscale-0-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.215
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: mariadb-repl-maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: mariadb-repl-maxscale-0  
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-repl-maxscale-1-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.216
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: mariadb-repl-maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: mariadb-repl-maxscale-1  
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-repl-maxscale-2-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.217
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: mariadb-repl-maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: mariadb-repl-maxscale-2  
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-repl-maxscale-3-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: $CIDR_PREFIX.0.218
spec:
  ports:
  - name: admin
    port: 8989
    protocol: TCP
    targetPort: 8989
  - name: rw-router-listener
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: rconn-master-router-listener
    port: 3307
    protocol: TCP
    targetPort: 3307
  - name: rconn-slave-router-listener
    port: 3308
    protocol: TCP
    targetPort: 3308
  selector:
    app.kubernetes.io/instance: mariadb-repl-maxscale
    app.kubernetes.io/name: maxscale
    statefulset.kubernetes.io/pod-name: mariadb-repl-maxscale-3  
  type: LoadBalancer
---