apiVersion: v2
name: mariadb-operator
description: Run and operate MariaDB in a cloud native way
home: https://github.com/mariadb-operator/mariadb-operator
icon: https://mariadb-operator.github.io/mariadb-operator/assets/mariadb_profile.svg
type: application
version: 0.35.1
appVersion: "0.35.1"
kubeVersion: ">=1.26.0-0"
maintainers:
  - email: martin.montes@mariadb.com
    name: mmontes11
  - email: pieter.humphrey@mariadb.com
    name: mariadb-pieterhumphrey
keywords:
  - mariadb
  - mysql
  - operator
  - mariadb-operator
  - database
  - maxscale
dependencies:
  - name: mariadb-operator-crds
    version: "0.35.1"
    condition: crds.enabled
    repository: file://../mariadb-operator-crds
