apiVersion: v2
name: mariadb-operator
description: Run and operate MariaDB in a cloud native way
home: https://github.com/mariadb-operator/mariadb-operator
icon: https://mariadb-operator.github.io/mariadb-operator/assets/mariadb_profile.svg
type: application
version: 0.29.0
appVersion: "v0.0.29"
kubeVersion: ">= 1.16.0-0"
maintainers:
  - name: mmontes11
    email: mariadb-operator@proton.me
keywords:
  - mariadb
  - mysql
  - operator
  - mariadb-operator
  - database
  - maxscale
