nameOverride: ""
fullnameOverride: ""

image:
  repository: mmontes11/mariadb-operator
  pullPolicy: IfNotPresent
  # -- The image tag to use. The default is the chart appVersion.
  tag: ""

# -- Controller log level
logLevel: INFO

# -- Cluster DNS name
clusterName: cluster.local

ha:
  # -- Enable high availability
  enabled: true
  # -- Number of replicas
  replicas: 3
  # -- Lease resource name to be used for leader election
  leaseId: database.mmontes.io

monitoring:
  # -- Enable prometheus metrics
  enabled: false
  # -- 'release' label to include in Prometheus resources
  prometheusRelease: ""

# -- Annotations to add to controller Pod
podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  # -- Resources to be added to the controller manager container
  manager: {}
  # requests:
  #   cpu: 10m
  #   memory: 32Mi
  # -- Resources to be added to the rbac proxy container
  rbacProxy: {}
  # requests:
  #   cpu: 10m
  #   memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}
