apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: maxscale-client
spec:
  mariaDbRef:
    name: mariadb-repl
  passwordSecretKeyRef:
    name: mariadb
    key: password
  maxUserConnections: 20
  host: "%" 
  retryInterval: 5s